config/routes.rb
Rails.application.routes.draw do
  
  root :to => redirect('/login')
    
  resources :users
  
  get '/apikeys'         => 'apikeys#show', as: :apikey
  get '/addAPI'          => 'apikeys#add'
  get '/delete'          => 'users#destroy'
  
  #post 'login'    => 'users#login',        :as => "/login"
  get '/login'    => 'users#login',        :as => "/login"
  get  '/logout'   => 'users#logout',       as:    :logout
  
  namespace :api do
    resources :users, :positions, :tags, :events
end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  include Rails.application.routes.url_helpers
  
  belongs_to :event
  #Handles user security
  has_secure_password :validations => false
  #Makes sure that the email is saved with lowercase letters.
  before_save { self.email = email.downcase }
  
  validates :username, 
            :presence => {:message => "Du måste ange ett användarnamn"},  
            :uniqueness => {:message => "Användarnamnet finns redan, välj ett annat."}, 
            length: { minimum: 3, message: "Användarnamnet är för kort, ange minst 3 tecken." }, 
            format: { with: /\A[a-zåäöA-ZÅÄÖ]+\z/, message: "Fältet 'användarnamn' innehåller otillåtna karaktärer" }
  
  validates :email, 
            :presence => {:message => "Du måste ange en epost"}, 
            :uniqueness => {:message => "E-posten finns redan, välj ett annat."},
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "Fältet 'email' innehåller otillåtna karaktärer" }
  
  validates :password, 
            :presence => {:message => "Du måste ange ett lösenord"},   
            confirmation: true, 
            length: { minimum: 6, message: "Lösenordet är för kort, ange minst 6 tecken." }, 
            format: { with: /\A[a-zåäöA-ZÅÄÖ]+\z/, message: "Fältet 'lösenord' innehåller otillåtna karaktärer." }
  
  def serializable_hash (options={})
    options = {
      only: [:id, :username, :email],
      methods: [:ref]
    }.update(options)
    
    super(options)
  end
  
  def ref
    { :href => "#{Rails.configuration.baseurl}#{api_user_path(self)}" }
  end


end

app/controllers/api/users_controller.rb
class UsersController < ApplicationController
  
  #before_action :api_key
  
  respond_to :json, :xml
  
  def index 
    users = User.limit(@limit).offset(@offset).includes(:event)
    
    # count existing users
    amountOfUsers = User.distinct.count(:id)
    
    respond_with users
  end
  
  def new
    #@user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    respond_with @user
  end
  
  def create
    user = User.new(user_params)
    # funkar inte än --> user.api_key = SecureRandom.hex
    
    if user.save
      respond_with user, status: :created
    else
      error = ErrorMessage.new("Could not create the resource. Bad parameters?", "Could not create the resource!")
      render json: error, status: :bad_request
    end
  end
  
  # Loginmethod
  def login
    u = User.find_by_email(params[:email])
    if u && u.authenticate(params[:password])
      session[:userid] = u.id
      redirect_to event_path
    else
      flash[:danger] = "Felaktigt användarnamn/lösenord!"
      redirect_to root_path
    end
  end
  
  # Logoutmethod
  def logout
    flash[:warning] = "Du är nu utloggad"
    session[:userid] = nil
    redirect_to root_path
  end
  
  # Method for removing API-keys
  def destroy
    @user = User.find(params[:id])
    @user.update_attribute(:api_key, nil)
    redirect_to apikey_path
  end
  
  private 
  
  def user_params
    json_params = ActionController::Parameters.new(JSON.parse(request.body.read))
    json_params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
  
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/create.html.erb
<div class="center jumbotron">
  <div class="text-center">
    <h1>Registrera ny användare</h1>
  </div>
</div>

<!-Form for registration->

<div class="row">
  <div class="col-md-6 col-md-offset-5">
<%= form_for @user do |f| %>
    <p><%= f.label :username %></p>
    <p><%= f.text_field :username %></p>
    <div class="control-group error">
      <%= @user.errors[:username] %>
    </div>
  
  <p><%= f.label :email %></p>
  <p><%= f.email_field :email %></p>
    <div class="control-group error">
      <%= @user.errors[:email] %>
    </div>
  
  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>
    <div class="control-group error">
      <%= @user.errors[:password] %>
    </div>
  
  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>
    <div class="control-group error">
      <%= @user.errors[:password_confirmation] %>
    </div>
  
  <p><%= f.submit "Registrera" %></p>
    
    <%= link_to "Tillbaka till inloggningsformuläret", root_path %>
  
  <% end %>
  </div>
</div>

app/views/user/new.html.erb
<div class="center jumbotron">
  <div class="text-center">
    <h1>Inloggning</h1>
  </div>
</div>

<% if flash[:notice] %>
<div class = "notice">
  <%= flash[:notice] %>
</div>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-5">
  <%= form_tag(login_path, method: "post")  do %>
  <p><%= label_tag(:email, "E-mail") %></p>
  <p><%= email_field_tag(:email) %></p>
  
  <p><%= label_tag(:password, "Lösenord") %></p>
  <p><%= password_field_tag(:password) %></p>
  
  <p><%= submit_tag("Logga in") %></p>
  <% end %>

    <%= link_to "Registrera ny användare", create_user_path %>
      </div>
</div>